# This is a simplified config where the rest of the
# settings are omitted and will be set by default.
bind: 0.0.0.0:25565
onlineMode: false
compression:
  threshold: 256
servers:
  server1: localhost:25566
try:
  - server1
